#!/usr/bin/env node
// Downloads the self-hosted webfonts into references/fonts/.
//
// Both families are SIL Open Font License 1.1, so redistributing the woff2 files
// inside this repo is fine as long as the licence files travel with them.
//
//   LXGW WenKai (霞鹜文楷)  — body + display, 97 unicode-range subsets per weight
//   JetBrains Mono          — code, latin only
//
// Run:  node scripts/fetch-fonts.mjs
// Idempotent: files that already exist with the expected size are skipped.

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'references', 'fonts');

const LXGW = { pkg: 'lxgw-wenkai-webfont', version: '1.7.0', weights: ['regular', 'bold'] };
const MONO = { pkg: '@fontsource/jetbrains-mono', version: '5.0.20', weights: [400, 700] };

const cdn = (pkg, version, file) => `https://cdn.jsdelivr.net/npm/${pkg}@${version}${file}`;
const meta = (pkg, version) => `https://data.jsdelivr.com/v1/packages/npm/${pkg}@${version}`;

async function getJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

async function getText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
}

// Walk the jsdelivr file listing and return every file as { name, size }.
function flatten(node, prefix = '') {
  const out = [];
  for (const f of node.files || []) {
    if (f.type === 'directory') out.push(...flatten(f, `${prefix}/${f.name}`));
    else out.push({ name: `${prefix}/${f.name}`, size: f.size });
  }
  return out;
}

async function download(url, dest, expectedSize) {
  try {
    const stat = await fs.stat(dest);
    if (!expectedSize || stat.size === expectedSize) return { skipped: true, size: stat.size };
  } catch {
    // not there yet
  }
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await fs.writeFile(dest, buf);
  return { skipped: false, size: buf.length };
}

// Run tasks with a small concurrency limit so we do not hammer the CDN.
async function pool(items, limit, worker) {
  const results = [];
  let i = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (i < items.length) {
        const index = i++;
        results[index] = await worker(items[index]);
      }
    })
  );
  return results;
}

await fs.mkdir(OUT, { recursive: true });

/* ── LXGW WenKai: 97 subset woff2 per weight ─────────────────── */
const lxgwFiles = flatten(await getJSON(meta(LXGW.pkg, LXGW.version)))
  .filter((f) => LXGW.weights.some((w) => f.name.startsWith(`/files/lxgwwenkai-${w}-subset-`)))
  .filter((f) => f.name.endsWith('.woff2'));

const lxgwResults = await pool(lxgwFiles, 8, (f) =>
  download(cdn(LXGW.pkg, LXGW.version, f.name), path.join(OUT, path.basename(f.name)), f.size)
);

/* ── JetBrains Mono: latin only, the two weights the stylesheet uses ── */
const monoFiles = MONO.weights.map((w) => `/files/jetbrains-mono-latin-${w}-normal.woff2`);
const monoResults = await pool(monoFiles, 4, (name) =>
  download(cdn(MONO.pkg, MONO.version, name), path.join(OUT, path.basename(name)))
);

/* ── fonts.css: concatenate the packages' own @font-face rules, repoint the URLs ── */
const chunks = [];

for (const weight of LXGW.weights) {
  const css = await getText(cdn(LXGW.pkg, LXGW.version, `/lxgwwenkai-${weight}.css`));
  chunks.push(css.replaceAll("url('./files/", "url('./"));
}

for (const weight of MONO.weights) {
  const css = await getText(cdn(MONO.pkg, MONO.version, `/latin-${weight}.css`));
  chunks.push(
    css
      // drop the .woff fallback — every browser we care about reads woff2
      .replace(/,\s*url\(\.\/files\/[^)]+\.woff\)\s*format\('woff'\)/g, '')
      .replaceAll('url(./files/', 'url(./')
  );
}

// Minified: this file is fetched on every page load and is larger than any single
// font subset, almost all of it unicode-range values. Only whitespace goes — the
// ranges themselves are untouched.
function minify(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')   // comments
    .replace(/\s+/g, ' ')                 // collapse all whitespace
    .replace(/\s*([{}:;,])\s*/g, '$1')    // no padding around punctuation
    .replace(/;}/g, '}')                  // drop the last semicolon in a block
    .trim();
}

const header =
  `/* Generated by scripts/fetch-fonts.mjs — do not edit. LXGW WenKai ${LXGW.version}` +
  ` + JetBrains Mono ${MONO.version}, SIL OFL 1.1, licences alongside. */\n`;

const raw = chunks.join('\n');
const minified = header + minify(raw);
await fs.writeFile(path.join(OUT, 'fonts.css'), minified);
const saved = raw.length - minified.length;

/* ── Licences ────────────────────────────────────────────────── */
// The fonts themselves are OFL 1.1 — take that text from each font's own repo.
// The npm package that repackages LXGW WenKai as webfonts is separately MIT, so
// ship that too rather than letting one licence stand in for the other.
await download(
  'https://raw.githubusercontent.com/lxgw/LxgwWenKai/main/OFL.txt',
  path.join(OUT, 'LICENSE-LXGWWenKai-OFL.txt')
);
await download(
  cdn(LXGW.pkg, LXGW.version, '/LICENSE'),
  path.join(OUT, 'LICENSE-LXGWWenKai-webfont-packaging-MIT.txt')
);
await download(
  'https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/OFL.txt',
  path.join(OUT, 'LICENSE-JetBrainsMono-OFL.txt')
);

/* ── Provenance ──────────────────────────────────────────────── */
const all = [...lxgwResults, ...monoResults];
const totalBytes = all.reduce((sum, r) => sum + r.size, 0);

await fs.writeFile(
  path.join(OUT, 'README.md'),
  `# references/fonts

由 \`scripts/fetch-fonts.mjs\` 生成，不要手改。重新抓取：\`node scripts/fetch-fonts.mjs\`

| 字体 | 用途 | 来源 | 版本 |
|---|---|---|---|
| LXGW WenKai 霞鹜文楷 | 正文 + 标题 | npm \`${LXGW.pkg}\` | ${LXGW.version} |
| JetBrains Mono | 代码 | npm \`${MONO.pkg}\` | ${MONO.version} |

两者字体本身均为 SIL Open Font License 1.1，授权原文见同目录 \`LICENSE-*-OFL.txt\`，随字体一起分发。
把霞鹜文楷重新打包成 webfont 的那个 npm 包另有 MIT 授权，一并收录为 \`LICENSE-LXGWWenKai-webfont-packaging-MIT.txt\`。

- 霞鹜文楷只打包 Regular(400) 与 Bold(700) 两个字重，各 97 个 \`unicode-range\` 分片。
  分片是刻意保留的：浏览器只下载页面上真正出现的字所在的分片，一门课的实际下载量远小于目录体积。
- JetBrains Mono 只打包 latin 子集的 400 与 700，不含斜体。
- \`fonts.css\` 由上游各字重的 CSS 拼接而成，仅把 \`./files/\` 路径改写为同目录相对路径。

字体文件：${all.length} 个，共 ${(totalBytes / 1048576).toFixed(2)} MB。
抓取日期：${new Date().toISOString().slice(0, 10)}
`
);

const fresh = all.filter((r) => !r.skipped).length;
console.log(`fonts: ${all.length} files, ${(totalBytes / 1048576).toFixed(2)} MB (${fresh} downloaded, ${all.length - fresh} already present)`);
console.log(
  `wrote ${path.relative(ROOT, path.join(OUT, 'fonts.css'))}: ` +
    `${(minified.length / 1024).toFixed(1)} KB minified, down from ${(raw.length / 1024).toFixed(1)} KB ` +
    `(saved ${(saved / 1024).toFixed(1)} KB, ${((saved / raw.length) * 100).toFixed(1)}%)`
);
console.log('wrote licences, README.md');
